import { describe, expect, test } from "bun:test";
import path from "node:path";
import process from "node:process";

const fixture = path.join(import.meta.dir, "fixtures", "path-config");
const cliRoot = path.resolve(import.meta.dir, "..");
const cliEntry = path.join(cliRoot, "src", "path-config.ts");
const adapterEntry = path.join(cliRoot, "src", "path-config-adapters.ts");
const oxlint = path.join(
  cliRoot,
  "node_modules",
  ".bin",
  process.platform === "win32" ? "oxlint.exe" : "oxlint"
);
const biomeBin = path.join(
  cliRoot,
  "node_modules",
  ".bin",
  process.platform === "win32" ? "biome.exe" : "biome"
);

describe("path-scoped provider configs", () => {
  test("Biome and ESLint native outputs retain the directory scope", async () => {
    const generated = Bun.spawnSync(
      [
        "bun",
        "-e",
        `import { resolvePathConfig } from ${JSON.stringify(cliEntry)}; import { materializePathConfig } from ${JSON.stringify(adapterEntry)}; const root = process.cwd(); const config = await resolvePathConfig(root, [root + "/ultracite.config.mjs", root + "/apps/web/ultracite.config.mjs"]); await materializePathConfig("biome", config); await materializePathConfig("eslint", config);`,
      ],
      { cwd: fixture }
    );
    expect(generated.exitCode).toBe(0);

    // SAFETY: This is generated by the Biome adapter immediately above in the child process.
    const biomeConfig = JSON.parse(
      await Bun.file(
        path.join(fixture, "node_modules/.cache/ultracite/biome.json")
      ).text()
    ) as { overrides: { includes?: string[] }[] };
    const eslint = await Bun.file(
      path.join(fixture, "node_modules/.cache/ultracite/eslint.config.mjs")
    ).text();

    expect(
      biomeConfig.overrides.some(
        (override) =>
          override.includes?.some((file) => file.startsWith("apps/web/")) &&
          !override.includes.some((file) => file.startsWith("packages/shared/"))
      )
    ).toBe(true);
    expect(eslint).toContain("apps/web/**/*");
    expect(eslint).toContain('scopeConfig(preset0, ["**/*"])');
    expect(eslint).toContain("export default");

    const lint = Bun.spawnSync(
      [
        biomeBin,
        "check",
        "--config-path=node_modules/.cache/ultracite/biome.json",
        "--no-errors-on-unmatched",
        "apps/web/src/bad-component.tsx",
        "apps/docs/src/bad-component.tsx",
        "packages/shared/src/bad-component.tsx",
        "packages/shared/src/native-rule.ts",
      ],
      { cwd: fixture }
    );
    const output = `${lint.stdout.toString()}${lint.stderr.toString()}`;
    expect(lint.exitCode).toBe(1);
    expect(output).toContain("useButtonType");
    expect(output).toContain("useJsxKeyInIterable");
    expect(output).not.toContain("apps\\docs\\src\\bad-component.tsx:");
    expect(output).not.toContain("packages\\shared\\src\\bad-component.tsx:");
  });

  test("Oxlint applies React diagnostics only to the nested workspace scope", () => {
    const materialize = Bun.spawnSync(
      [
        "bun",
        "-e",
        `import { writeFileSync, rmSync } from "node:fs"; import { resolvePathConfig } from ${JSON.stringify(cliEntry)}; import { materializePathConfig } from ${JSON.stringify(adapterEntry)}; const root = process.cwd(); const nativeConfig = root + "/.oxlintrc.json"; writeFileSync(nativeConfig, JSON.stringify({ rules: { "no-alert": "error" } })); const config = await resolvePathConfig(root, [root + "/ultracite.config.mjs", root + "/apps/web/ultracite.config.mjs"]); await materializePathConfig("oxlint", config); rmSync(nativeConfig);`,
      ],
      { cwd: fixture }
    );
    expect(materialize.exitCode).toBe(0);

    const lint = Bun.spawnSync(
      [
        oxlint,
        "--config",
        "node_modules/.cache/ultracite/oxlint.config.mjs",
        "--format",
        "unix",
        "apps/web/src/bad-component.tsx",
        "apps/docs/src/bad-component.tsx",
        "packages/shared/src/bad-component.tsx",
        "packages/shared/src/native-rule.ts",
      ],
      { cwd: fixture }
    );
    const output = `${lint.stdout.toString()}${lint.stderr.toString()}`;
    expect(lint.exitCode).toBe(1);
    expect(output).toContain("react(button-has-type)");
    expect(output).toContain("react(jsx-key)");
    expect(output).toContain("apps/web/src/bad-component.tsx");
    expect(output).not.toContain("apps/docs/src/bad-component.tsx:");
    expect(output).not.toContain("packages/shared/src/bad-component.tsx:");
    expect(output).toContain("packages/shared/src/native-rule.ts");
    expect(output).toContain("eslint(no-alert)");
  });

  test("root check and fix materialize the shared DSL for explicit cross-scope files", () => {
    const runCommands = Bun.spawnSync(
      [
        process.execPath,
        "-e",
        `import { writeFileSync, rmSync } from "node:fs"; import { spawnSync } from "node:child_process"; import path from "node:path"; const root = process.cwd(); const manifest = path.join(root, "apps/web/package.json"); const nativeConfig = path.join(root, ".oxlintrc.json"); writeFileSync(nativeConfig, JSON.stringify({ rules: { "no-alert": "error" } })); writeFileSync(manifest, "{}\\n"); writeFileSync(path.join(root, "apps/web/src/clean.ts"), "export const clean = 1;\\n"); writeFileSync(path.join(root, "packages/shared/src/clean.ts"), "export const clean = 1;\\n"); const cli = ${JSON.stringify(path.join(cliRoot, "src", "index.ts"))}; const env = { ...process.env, PATH: ${JSON.stringify(path.join(cliRoot, "node_modules", ".bin"))} + path.delimiter + process.env.PATH }; const check = spawnSync(process.execPath, [cli, "check", "--format=unix", "apps/web/src/clean.ts", "packages/shared/src/clean.ts"], { cwd: root, encoding: "utf-8", env }); const fix = spawnSync(process.execPath, [cli, "fix", "--format=unix", "apps/web/src/clean.ts", "packages/shared/src/clean.ts"], { cwd: root, encoding: "utf-8", env }); rmSync(manifest); rmSync(nativeConfig); console.log(JSON.stringify({ checkStatus: check.status, checkOutput: check.stdout + check.stderr, fixStatus: fix.status, fixOutput: fix.stdout + fix.stderr }));`,
      ],
      { cwd: fixture }
    );
    expect(runCommands.exitCode).toBe(0);
    // SAFETY: The subprocess prints the result object constructed in the inline integration script.
    const result = JSON.parse(runCommands.stdout.toString()) as {
      checkOutput: string;
      checkStatus: number | null;
      fixOutput: string;
      fixStatus: number | null;
    };
    expect(result.checkStatus).toBe(0);
    expect(result.fixStatus).toBe(0);
    expect(result.checkOutput).not.toContain("Could not resolve");
    expect(result.fixOutput).not.toContain("Could not resolve");
  });
});
